# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://inspiring-wilson-e8a42b.netlify.com'
baseurl: ''
title: 'DunjunHexplorer Blog'
description: 'just talkin bout stuff'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=136"

# Pagination
paginate: 5
paginate_path: page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "we gonna make some stuff :)"
