# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: ''
baseurl: ''
title: 'DunjunHexplorer Blog'
description: 'just talkin bout stuff'
permalink: pretty
logo: "https://secure.gravatar.com/avatar/61fdbdcb21a5bfc7d0bfd974fdc60703"

# Pagination
paginate: 5
paginate_path: page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "we gonna make some stuff :)"
